server.port=${SERVER_PORT:8080}
spring.application.name=pharmacy-backend
spring.mvc.pathmatch.matching-strategy=ant_path_matcher
spring.jackson.serialization.write-dates-as-timestamps=false
logging.level.com.pharmacy=INFO
